"""empty message

Revision ID: 1ad28b02e3de
Revises: f09aeea42a65
Create Date: 2019-09-07 19:59:22.610182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad28b02e3de'
down_revision = 'f09aeea42a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.add_column('follow', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.drop_constraint('follow_followed_fkey', 'follow', type_='foreignkey')
    op.drop_constraint('follow_follower_fkey', 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'user', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'user', ['follower_id'], ['id'])
    op.drop_column('follow', 'follower')
    op.drop_column('follow', 'followed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('followed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follow', sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key('follow_follower_fkey', 'follow', 'user', ['follower'], ['id'])
    op.create_foreign_key('follow_followed_fkey', 'follow', 'user', ['followed'], ['id'])
    op.drop_column('follow', 'follower_id')
    op.drop_column('follow', 'followed_id')
    # ### end Alembic commands ###
