"""empty message

Revision ID: 59b6416ef54e
Revises: 
Create Date: 2019-09-11 14:37:56.468930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b6416ef54e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
