"""empty message

Revision ID: 5f09d901c32a
Revises: f4eee5f7068b
Create Date: 2019-09-07 19:43:28.232581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f09d901c32a'
down_revision = 'f4eee5f7068b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follow_followed_fkey', 'follow', type_='foreignkey')
    op.drop_column('follow', 'followed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('followed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('follow_followed_fkey', 'follow', 'user', ['followed'], ['id'])
    # ### end Alembic commands ###
