"""empty message

Revision ID: f09aeea42a65
Revises: 5f09d901c32a
Create Date: 2019-09-07 19:54:35.875453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09aeea42a65'
down_revision = '5f09d901c32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('followed', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'follow', 'user', ['followed'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_column('follow', 'followed')
    # ### end Alembic commands ###
